auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: tsuish's blog
url: http://bittsui.github.io
feed: /atom.xml
author_info: <a href="http://bittsui.github.io/">bittsui</a>
favicon: "/images/favicon.ico"


myblog:
  gavatar: c3e584693e41773b3ff808324653c2f4
  gpname: bittsui
  # linkedin: https://meiriyiwen.com/
  github: http://www.github.com/bittsui
  coverimgs: >
    'url("https://raw.githubusercontent.com/BitTsui/bittsui.github.io/master/images/background2.jpg")'
  postbgimg: https://raw.githubusercontent.com/BitTsui/bittsui.github.io/master/images/1000141.jpg

prose:
  rooturl: "_posts"
  # siteurl: "http://bittsui.github.io/"
  media: "images"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "published"
        field:
          element: "hidden"
          value: "true"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
