auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: tsuish's blog
url: http://bittsui.github.io
feed: /atom.xml
author_info: <a href="http://bittsui.github.io/">bittsui</a>

myblog:
  gavatar: c3e584693e41773b3ff808324653c2f4
  gpname: bittsui
  # linkedin: https://meiriyiwen.com/
  github: http://www.github.com/bittsui?tab=repositories
  coverimgs: >
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-QCTQNpn/0/X3/IMG_3940-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-zvPmxS6/0/X3/IMG_3006-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-mt6dbQD/0/X3/IMG_5953-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-BW2MzfC/0/X3/IMG_3402-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-HwZrx3V/0/X3/IMG_3374-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-HwZrx3V/0/X3/IMG_3374-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-3mqdZgt/0/X3/IMG_2301-X3.jpg")',
    'url("http://liyu1981.smugmug.com/Photography/365-days-365-photos/i-MpHzMZ7/0/X3/IMG_1448-X3.jpg")'
  postbgimg: https://raw.githubusercontent.com/BitTsui/bittsui.github.io/master/images/1000141.jpg

prose:
  rooturl: "_posts"
  # siteurl: "http://bittsui.github.io/"
  media: "images"
  metadata:
    _posts/blog:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          placeholder: "Input your title here"
          type: "text"

      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Input your abstract here"
          type: "text"

      - name: "layout"
        field:
          element: "hidden"
          value: "post"

      - name: "published"
        field:
          element: "hidden"
          value: "true"

      - name: "category"
        field:
          element: "hidden"
          value: "blog"
